SET SQL_SAFE_UPDATES = 0;

-- APAGANDO BANCO DE DADOS SE EXISTIR
DROP DATABASE IF EXISTS DBTAXI;
-- CRIANDO BANCO DE DADOS
CREATE DATABASE DBTAXI;
USE DBTAXI;

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(150) NOT NULL
    , ENDERECO VARCHAR(150) NOT NULL
    , TELEFONE VARCHAR(11) NOT NULL
    , CPF VARCHAR(11) NOT NULL
    , RG VARCHAR(9) NOT NULL 
    , PRIMARY KEY (IDCLIENTE)
);

CREATE TABLE MOTORISTA (
	IDMOTORISTA INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(150) NOT NULL
    , ENDERECO VARCHAR(150) NOT NULL
    , TELEFONE VARCHAR(11) NOT NULL
    , CNH VARCHAR(9) NOT NULL
    , PRIMARY KEY (IDMOTORISTA)
);

CREATE TABLE VEICULO (
	IDVEICULO INT NOT NULL AUTO_INCREMENT
	, PLACA VARCHAR(10) NOT NULL
    , MODELO VARCHAR(50) NOT NULL
    , ANO INT NOT NULL
    , COR VARCHAR(50) NOT NULL
    , MARCA VARCHAR(50) NOT NULL
    , PRIMARY KEY (IDVEICULO)
);

CREATE TABLE CHAMADO (
	IDCHAMADO INT NOT NULL AUTO_INCREMENT
    , IDCLIENTE INT NOT NULL
    , IDMOTORISTA INT NOT NULL
    , IDVEICULO INT NOT NULL
    , ORIGEM VARCHAR(150) NOT NULL
    , DESTINO VARCHAR(150) NOT NULL
    , TIPO VARCHAR(50) NOT NULL
    , KM_INICIAL DECIMAL(10,3) NOT NULL
    , KM_FINAL DECIMAL(10,3) NOT NULL
    , HORA_INICIAL TIMESTAMP NOT NULL
    , HORA_FINAL TIMESTAMP 
    , VALOR_TOTAL DECIMAL(10,2) NOT NULL
    , PRIMARY KEY (IDCHAMADO)
    , FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE (IDCLIENTE)
    , FOREIGN KEY (IDMOTORISTA) REFERENCES MOTORISTA (IDMOTORISTA)
    , FOREIGN KEY (IDVEICULO) REFERENCES VEICULO (IDVEICULO)
);